### ISSUE TITLE
Add Typescript Support

### ISSUE THREAD

**Issue by arafatzahan** [web-ridge/create-react-native-web-application#2]
First of all, thank you for making this. It's a great step towards cross platform apps. 

Would you consider adding typescript support? It will be a great addition. 

Much love. <3

Thank you!

**Comment by RichardLindhout** [comment]
The output is in Typescript by default, the source code of the library too in the /src directory

**Comment by arafatzahan** [comment]
@RichardLindhout Wow now I feel EXTREMELY stupid. Maybe it would be a good idea to mention that the generated project is TS Project in the Readme? 

Cheers

**Comment by RichardLindhout** [comment]
Good idea, will do!
