### ISSUE TITLE
Provide a working example of <image source={require(...)}> please

### ISSUE THREAD

**Issue by jkoutavas** [web-ridge/create-react-native-web-application#7]
Can someone please provide a working example of using static images for `<image>`?  I'm unable to succeed with what's covered in [react-native-web issue #1497](https://github.com/necolas/react-native-web/issues/1497#issuecomment-761947037) as a solution for this request. Thank you so much.

**Comment by jkoutavas** [comment]
I've simplified the problem down by building a minimal javascript example app, not using create-react-native-web-application. So, I'm ruling out its an issue with your fine template, nor is it somehow TypeScript/webpack related.

Example app is here, if you're interested: https://github.com/jkoutavas/react-native-web-static-image

**Comment by RichardLindhout** [comment]
Require should work fine but you can also import on top like described in create-react-app. You should not add anything it should work out of the box.

But React Native Web image required to have width/height specified
